program: examples/examples_src/train_mlmc.py
method: grid

parameters:
  wandb_exp_idx:
    values: [0]

  data_dir:
    value: examples/pdes/jeb/data
  dataset:
    value: jeb
  normalize:
    value: false
  base_res:
    value: 6
  c2f_resolutions:
    value: [2, 3, 4, 6]
  total_samples:
    value: 1924

  model:
    value: ginot
  ginot_in_dim:
    value: 3
  ginot_global_pooling:
    value: true
  ginot_latent_dim:
    value: 64
  ginot_embed_dim:
    value: 64
  ginot_num_layers:
    value: 4
  ginot_num_heads:
    value: 4
  ginot_padding_value:
    value: -1000
  ginot_dropout:
    value: 0.0
  ginot_cross_attn_layers:
    value: 4
  ginot_in_channels:
    value: 3
  ginot_out_channels:
    value: 1
  ginot_emd_version:
    value: nerf
  ginot_coarse_pc:
    value: false

  mlmc_pairing:
    values: [hierarchy]
  mlmc_hierarchy_cache:
    values: [true, false]
  mlmc_sampling_style:
    value: geom_prog
  mlmc_batch_style:
    value: geom_prog_batch
  mlmc_both_multiplier:
    values: [1, 2]
  mlmc_max_level:
    values: [3]

  batch_size:
    value: 8
  epochs:
    value: 400
  lr:
    values: [0.001]
  optimizer:
    value: adam
  weight_decay:
    value: 0.0001
  loss_type:
    value: ginot
  loss_reduction:
    value: mean
  device:
    value: cuda
  seed:
    value: 42
  gradient_accumulation_steps:
    value: 1

  use_scheduler:
    value: true
  step_size:
    value: 100
  gamma:
    value: 0.7

  eval_every:
    value: 10
  eval_plot_every:
    value: 50
  eval_grad_every:
    value: null
  eval_grad_mode:
    value: raw
  eval_grad_rand:
    value: false
  eval_grad_batches:
    value: 1
  save_model:
    value: false
  save_wandb_artifact:
    value: false

command:
  - ${env}
  - python
  - ${program}
  - --config
  - examples/pdes/jeb/configs/jeb_ginot_mlmc.yaml
  - ${args}
  - --use_wandb
  - --wandb_sweep

entity: mlmc-optim
project: jeb_ginot_mlmc_new
